=begin
#Backscatter.io

#[This is the Backscatter.io API.](https://backscatter.io/developers) 

OpenAPI spec version: 1.0.0
Contact: info@backscatter.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Hello
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Hello' do
  before do
    # run before each test
    @instance = SwaggerClient::Hello.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Hello' do
    it 'should create an instance of Hello' do
      expect(@instance).to be_instance_of(SwaggerClient::Hello)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
